before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
  - tar xzvf apache-maven-3.6.1-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.1/bin:$PATH
  - mvn -v
language: java
script: travis_wait 60 mvn compile -Pnolog
jdk:
  - openjdk8
branches:
  only:
    - master
